version: '3.9'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SHEDRACKs.677
      MYSQL_DATABASE: student
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net

  # API (Backend)
  api:
    build: .
    container_name: student-api
    restart: always
    ports:
      - "3006:3006"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-net

  # Front-End 1 (React)
  frontend1:
    build:
      context: ./student-frontend/frontend
    container_name: frontend1
    restart: always
    ports:
      - "3001:80"
    networks:
      - app-net

  # Front-End 2 (React)
  frontend2:
    build:
      context: ./student-frontend/frontend
    container_name: frontend2
    restart: always
    ports:
      - "3002:80"
    networks:
      - app-net

  # Front-End 3 (React)
  frontend3:
    build:
      context: ./student-frontend/frontend
    container_name: frontend3
    restart: always
    ports:
      - "3003:80"
    networks:
      - app-net

  # NGINX Load Balancer
  nginx:
    image: nginx:alpine
    container_name: load-balancer
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your nginx.conf here
    ports:
      - "80:80"
    networks:
      - app-net

volumes:
  mysql-data:

networks:
  app-net:
