services:
  frontend1:
    build: ./student-frontend
    container_name: frontend1
    networks:
      - frontend_studentnet

  frontend2:
    build: ./student-frontend
    container_name: frontend2
    networks:
      - frontend_studentnet

  frontend3:
    build: ./student-frontend
    container_name: frontend3
    networks:
      - frontend_studentnet

  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend_studentnet

networks:
  frontend_studentnet:
    driver: bridge
